import type{NavigationAction}from'./types';
const a=(id:string,origin:string,label:string,type:NavigationAction['type'],destination:string|undefined,roles:string[],evidence:string,status:NavigationAction['status']='working',condition?:string,issue?:string,stateChange?:string):NavigationAction=>({id,origin,label,type,destination,roles,evidence,status,condition,issue,stateChange});

export const navigationActions:NavigationAction[]=[
 a('welcome-start','welcome','Comenzar','button','/onboarding',['Público'],'MiLaPazApp.tsx:28'),
 a('welcome-visitor','welcome','Explorar como visitante','button','/inicio',['Visitante'],'MiLaPazApp.tsx:28','partial',undefined,'Navega, pero no actualiza session.visitor.'),
 a('onboarding-next','onboarding','Siguiente','button',undefined,['Público'],'MiLaPazApp.tsx:29','working','Mientras queden diapositivas',undefined,'Incrementa el paso'),
 a('onboarding-login','onboarding','Iniciar ahora / Omitir introducción','button','/login',['Público'],'MiLaPazApp.tsx:29'),
 a('login-verify','login','Recibir código','form','/verify',['Público'],'MiLaPazApp.tsx:30','working','CI >= 6 y celular >= 8 caracteres'),
 a('login-visitor','login','Explorar como visitante','button','/inicio',['Visitante'],'MiLaPazApp.tsx:30','partial',undefined,'No actualiza session.visitor.'),
 a('login-help','login','Necesito ayuda','button','/ayuda',['Público'],'MiLaPazApp.tsx:30'),
 a('verify-success','verify','Verificar y continuar','form','/inicio',['Ciudadano'],'MiLaPazApp.tsx:31','partial','Código 123456','Navega, pero no actualiza session.authenticated.'),
 a('verify-resend','verify','Reenviar en 00:24','button',undefined,['Público'],'MiLaPazApp.tsx:31','broken',undefined,'Botón sin controlador ni estado de reenvío.'),
 a('shell-demo','citizen-shell','Demo','button','/demo',['Ciudadano','Visitante'],'MiLaPazApp.tsx:33'),
 a('shell-profile','citizen-shell','Avatar','button','/perfil',['Ciudadano','Visitante'],'MiLaPazApp.tsx:33'),
 a('shell-notifications','citizen-shell','Campana','button','/notificaciones',['Ciudadano','Visitante'],'MiLaPazApp.tsx:33'),
 a('shell-help','citizen-shell','SOS','button','/ayuda',['Ciudadano','Visitante'],'MiLaPazApp.tsx:33'),
 ...[['bottom-home','Inicio','/inicio'],['bottom-services','Servicios','/servicios'],['bottom-map','Mapa','/mapa'],['bottom-notices','Avisos','/notificaciones'],['bottom-profile','Perfil','/perfil']].map(([id,label,destination])=>a(id,'citizen-shell',label,'tab',destination,['Ciudadano','Visitante'],'MiLaPazApp.tsx:12-33')),
 ...[['home-health','Salud','/salud'],['home-transport','Transporte','/transporte'],['home-report','Reportar problema','/reportes/nuevo'],['home-pets','Mascotas','/mascotas'],['home-courts','Canchas','/canchas'],['home-alerts','Alertas','/alertas']].map(([id,label,destination])=>a(id,'home',label,'card',destination,['Ciudadano','Visitante'],'DemoModules.tsx:21')),
 a('home-search','home','Buscador','form','/servicios',['Ciudadano','Visitante'],'DemoModules.tsx:21','working','Al recibir foco'),
 a('home-appointment','home','Ver cita y acciones','button','/salud/citas/demo',['Ciudadano'],'DemoModules.tsx:21'),
 a('home-active-alert','home','Alerta activa','card','/alertas',['Ciudadano','Visitante'],'DemoModules.tsx:21','working','alert.active'),
 a('home-report-detail','home','Último reporte','card','/reportes/[code]',['Ciudadano'],'DemoModules.tsx:21'),
 a('services-open','services','Abrir módulo encontrado','card','Ruta del módulo',['Ciudadano','Visitante'],'DemoModules.tsx:23'),
 a('help-orientation','help','Hablar con orientación ciudadana','button',undefined,['Ciudadano','Visitante'],'DemoModules.tsx:19','working',undefined,undefined,'Muestra confirmación simulada'),
 a('help-services','help','Buscar un servicio','button','/servicios',['Ciudadano','Visitante'],'DemoModules.tsx:19'),
 a('help-report','help','Reportar un problema urbano','button','/reportes/nuevo',['Ciudadano','Visitante'],'DemoModules.tsx:19'),
 ...[['health-book','Solicitar cita','/salud/reservar'],['health-receipt','Ver comprobante','/salud/citas/demo'],['health-queue','Fila virtual','/salud/fila'],['health-caregiver','Familiar autorizado','/salud/familiar'],['health-history','Historial clínico','/salud/historial']].map(([id,label,destination])=>a(id,'health',label,'button',destination,['Ciudadano'],'DemoModules.tsx:26')),
 a('booking-next','health-booking','Continuar','button',undefined,['Ciudadano'],'DemoModules.tsx:27','working','Debe seleccionar una opción','', 'Avanza establecimiento → especialidad → profesional → fecha → hora'),
 a('booking-confirm','health-booking','Confirmar cita','button','/salud/citas/demo',['Ciudadano'],'DemoModules.tsx:27','working','Cinco selecciones completas',undefined,'Guarda cita y notificación'),
 a('appointment-confirm','appointment-receipt','Confirmar asistencia','button',undefined,['Ciudadano'],'DemoModules.tsx:28','working',undefined,undefined,'Estado Confirmada'),
 a('appointment-reprogram','appointment-receipt','Reprogramar','button','/salud/reservar',['Ciudadano'],'DemoModules.tsx:28','partial',undefined,'Abre un formulario nuevo; no precarga una intención de reprogramación.'),
 a('appointment-cancel','appointment-receipt','Cancelar cita','button',undefined,['Ciudadano'],'DemoModules.tsx:28','working',undefined,undefined,'Estado Cancelada y notificación'),
 a('queue-arrive','health-queue','Avisar que llegué','button',undefined,['Ciudadano'],'DemoModules.tsx:29','working','No haber marcado llegada',undefined,'Estado Paciente presente'),
 a('caregiver-save','health-caregiver','Guardar autorización','button','/perfil',['Ciudadano'],'DemoModules.tsx:30','working','Al menos un permiso',undefined,'Persiste cuidador y notificación'),
 a('clinical-share','clinical-history','Compartir acceso temporal','button','/salud/historial/compartir',['Ciudadano'],'DemoModules.tsx:32'),
 a('clinical-generate','clinical-share','Generar QR temporal','form',undefined,['Ciudadano'],'DemoModules.tsx:32','working','Código 123456 y categorías seleccionadas',undefined,'Token de 15 minutos y un uso'),
 a('clinical-revoke','clinical-share','Revocar acceso','button',undefined,['Ciudadano'],'DemoModules.tsx:32','working','Token generado',undefined,'Estado Revocado'),
 a('transport-search','transport','Calcular ruta multimodal','form','/transporte/multimodal',['Ciudadano','Visitante'],'DemoModules.tsx:34','working','Origen y destino no vacíos'),
 a('transport-block','multimodal-route','Simular bloqueo','button',undefined,['Ciudadano','Visitante'],'DemoModules.tsx:35','working',undefined,undefined,'Alterna ruta normal y alternativa'),
 a('transport-start','multimodal-route','Iniciar recorrido','button',undefined,['Ciudadano','Visitante'],'DemoModules.tsx:35','working',undefined,undefined,'started=true'),
 a('transport-save','multimodal-route','Guardar ruta','button','/perfil',['Ciudadano'],'DemoModules.tsx:35','working',undefined,undefined,'saved=true y notificación'),
 a('reports-new','reports-list','Nuevo','button','/reportes/nuevo',['Ciudadano'],'UnifiedReports.tsx:6'),
 a('reports-open','reports-list','Abrir reporte','card','/reportes/[code]',['Ciudadano'],'UnifiedReports.tsx:6'),
 a('report-support','report-new','Apoyar y agregar evidencia','button','/reportes/[code]',['Ciudadano'],'UnifiedReports.tsx:7','working','Coincidencia por categoría y zona',undefined,'Agrega evidencia al caso existente'),
 a('report-submit','report-new','Enviar reporte','form','/reportes/[code]',['Ciudadano'],'UnifiedReports.tsx:7','working','Categoría, zona, descripción y foto',undefined,'Crea caso Recibido'),
 a('report-chat','report-detail','Enviar mensaje','form',undefined,['Ciudadano'],'UnifiedReports.tsx:8','working','Texto no vacío',undefined,'Mensaje, historial y notificación'),
 a('report-rate','report-detail','Calificar 1–5','button',undefined,['Ciudadano'],'UnifiedReports.tsx:9','working','Estado Resuelto',undefined,'Persiste rating'),
 a('report-reopen','report-detail','Solicitar reapertura','button',undefined,['Ciudadano'],'UnifiedReports.tsx:9','working','Estado Resuelto',undefined,'Estado Reabierto'),
 a('pets-register-open','pets-list','Registrar','button','/mascotas/nueva',['Ciudadano'],'DemoModules.tsx:38'),
 a('pets-alert-open','pets-list','Ver alerta','button','/mascotas/alertas/kira',['Ciudadano'],'DemoModules.tsx:38','working','Mascota registrada'),
 a('pets-register','pet-registration','Guardar y generar credencial','form','/mascotas',['Ciudadano'],'DemoModules.tsx:39','working','Nombre y zona',undefined,'Persiste mascota pendiente de revisión'),
 a('pets-sighting','pet-alert','Enviar avistamiento','form',undefined,['Ciudadano','Visitante'],'DemoModules.tsx:40','working','Descripción >= 8',undefined,'Posible avistamiento y notificación'),
 a('pets-close','pet-alert','Marcar reunida y cerrar','button','/mascotas',['Ciudadano'],'DemoModules.tsx:40','working','Alerta no cerrada',undefined,'Estado Cerrada'),
 a('courts-book-open','courts-list','Ver disponibilidad y reservar','button','/canchas/reservar',['Ciudadano'],'DemoModules.tsx:43'),
 a('courts-filter','courts-list','Filtrar canchas','tab',undefined,['Ciudadano','Visitante'],'DemoModules.tsx:43','partial',undefined,'Cambia el filtro, pero solo existe una cancha visible.'),
 a('courts-damage','courts-list','Reportar daños o accesibilidad','link','/reportes/nuevo',['Ciudadano'],'DemoModules.tsx:43'),
 a('courts-reserve','court-booking','Confirmar reserva simulada','form','/canchas',['Ciudadano'],'DemoModules.tsx:44','working','Reglamento, participantes y sin reserva activa',undefined,'Persiste reserva y notificación'),
 a('courts-cancel','courts-list','Cancelar reserva','button',undefined,['Ciudadano'],'DemoModules.tsx:43','working','Reserva confirmada',undefined,'Estado Cancelada'),
 a('alerts-view','home','Abrir alerta activa','card','/alertas',['Ciudadano','Visitante'],'DemoModules.tsx:21'),
 a('map-layer','city-map','Seleccionar capa','tab',undefined,['Ciudadano','Visitante'],'MiLaPazApp.tsx:54','working',undefined,undefined,'Cambia el punto seleccionado'),
 a('map-detail','city-map','Ver detalle','button','Ruta según capa',['Ciudadano','Visitante'],'MiLaPazApp.tsx:54','working'),
 a('notification-open','notifications','Abrir notificación','notification','Destino almacenado',['Ciudadano'],'DemoModules.tsx:47','working',undefined,undefined,'Marca como leída y navega'),
 a('notification-read-all','notifications','Marcar todas','button',undefined,['Ciudadano'],'DemoModules.tsx:47','working',undefined,undefined,'read=true'),
 a('profile-logout','profile','Cerrar sesión','button','/',['Ciudadano'],'UnifiedProfile.tsx:2','working',undefined,undefined,'Limpia estado de sesión, conserva datos demo'),
 a('demo-role','demo','Seleccionar rol','card','Ruta inicial del rol',['Demostración'],'DemoModules.tsx:15','working',undefined,undefined,'Actualiza role'),
 a('demo-reset','demo','Restablecer demo','button',undefined,['Demostración'],'DemoModules.tsx:15','working',undefined,undefined,'Restaura semilla local'),
 a('demo-system-docs','demo','Documentación del sistema','link','/equipo/mapa-sistema',['Demostración'],'DemoModules.tsx:15'),
 a('admin-report-open','admin-reports','Gestionar','button','/admin/reportes/[code]',['Encargado municipal','Administrador'],'UnifiedAdminReports.tsx:3'),
 a('admin-report-chat','admin-report-detail','Enviar mensaje','form',undefined,['Encargado municipal','Administrador'],'UnifiedAdminReports.tsx:4','working','Texto no vacío',undefined,'Mensaje y notificación ciudadana'),
 a('admin-report-evidence','admin-report-detail','Evidencia de trabajo','button',undefined,['Encargado municipal','Administrador'],'UnifiedAdminReports.tsx:4','working',undefined,undefined,'Agrega evidencia de resolución'),
 a('admin-report-save','admin-report-detail','Guardar cambios','form',undefined,['Encargado municipal','Administrador'],'UnifiedAdminReports.tsx:5','working','Unidad al asignar; motivo al rechazar; evidencia al resolver',undefined,'Actualiza caso y notifica'),
 ...[['admin-health-confirm','Confirmar cita','Confirmada'],['admin-health-arrive','Marcar llegada','Paciente presente'],['admin-health-next','Llamar siguiente','En espera'],['admin-health-room','Cambiar consultorio','Consultorio 08'],['admin-health-complete','Completar atención','Completada']].map(([id,label,stateChange])=>a(id,'admin-health',label,'button',undefined,['Encargado de salud','Administrador'],'DemoModules.tsx:55','working',undefined,undefined,stateChange)),
 a('medical-close','medical-access','Registrar atención y cerrar acceso','form','/salud/historial',['Médico','Administrador'],'DemoModules.tsx:56','working','Token activo no vencido y observación >= 8',undefined,'Consume token y registra auditoría'),
 ...[['pet-approve','Aprobar','Publicada'],['pet-correct','Solicitar corrección','Requiere corrección'],['pet-reject','Rechazar','Rechazada'],['pet-admin-close','Cerrar alerta','Cerrada']].map(([id,label,stateChange])=>a(id,'admin-pets',label,'button',undefined,['Moderador de mascotas','Administrador'],'DemoModules.tsx:57','working',undefined,undefined,stateChange)),
 a('sports-confirm','admin-courts','Confirmar reserva','button','/canchas',['Encargado deportivo','Administrador'],'DemoModules.tsx:58','working','Existe reserva',undefined,'Confirma y notifica'),
 a('alerts-publish','admin-alerts','Publicar alerta','form','/alertas',['Administrador'],'DemoModules.tsx:59','partial','Título >= 8','Nivel y zona visibles no se persisten; solo se actualiza el título.'),
 a('alerts-close','admin-alerts','Finalizar alerta','button','/alertas',['Administrador'],'DemoModules.tsx:59','working','Alerta activa',undefined,'active=false y notificación'),
 a('admin-docs','admin-shell','Documentación','link','/equipo/mapa-sistema',['Encargado municipal','Encargado de salud','Médico','Moderador de mascotas','Encargado deportivo','Administrador'],'DemoModules.tsx:53'),
 a('docs-wireflow','system-map','Abrir wireflow','link','/equipo/flujo-navegacion',['Documentación interna'],'NavigationDocumentation.tsx'),
 a('wireflow-open','navigation-wireflow','Abrir pantalla','link','Ruta de la tarjeta',['Documentación interna'],'NavigationWireflow.tsx')
];
