import{navigationActions}from'./actions';import type{NavigationScreen,NavigationScreenDefinition}from'./types';
const s=(id:string,name:string,route:string,roles:string[],module:string,component:string,layout:string,access:string,back:string,status:NavigationScreenDefinition['status'],notes:string,condition?:string):NavigationScreenDefinition=>({id,name,route,roles,module,component,layout,access,back,status,notes,condition});

const definitions:NavigationScreenDefinition[]=[
 s('welcome','Bienvenida','/',['Público'],'Acceso','Welcome','Sin shell','URL directa','No aplica','implemented','Entrada pública del prototipo.'),
 s('onboarding','Onboarding','/onboarding',['Público'],'Acceso','Onboarding','Sin shell','Comenzar','Omitir o finalizar','implemented','Tres pasos controlados por estado local.'),
 s('login','Inicio de sesión','/login',['Público'],'Acceso','Login','Sin shell','Onboarding','Volver a bienvenida','simulated','Valida formato local; no autentica contra servidor.'),
 s('verify','Verificación de celular','/verify',['Público'],'Acceso','Verify','Sin shell','Formulario de login','Volver a login','partial','Código fijo 123456; reenvío desconectado.'),
 s('demo','Selector de demostración','/demo',['Demostración'],'Acceso','DemoSelector','Sin shell','Cabecera ciudadana o panel','Seleccionar un rol','implemented','Siete roles, reinicio y documentación.'),
 s('home','Inicio ciudadano','/inicio',['Ciudadano','Visitante'],'Inicio','UnifiedHome','Shell ciudadano','Login, visitante o navegación inferior','Navegación inferior','implemented','Resume entidades compartidas.'),
 s('services','Servicios ciudadanos','/servicios',['Ciudadano','Visitante'],'Servicios','ServicesHub','Shell ciudadano','Inicio o navegación inferior','Navegación inferior','implemented','Buscador local de seis módulos.'),
 s('help','Ayuda y orientación','/ayuda',['Público','Ciudadano','Visitante'],'Ayuda','HelpCenter','Shell ciudadano','Login o botón SOS','Volver a inicio','simulated','No contacta canales reales.'),
 s('city-map','Mapa ciudadano','/mapa',['Ciudadano','Visitante'],'Mapa','MapScreen','Shell ciudadano','Navegación inferior','Navegación inferior','simulated','Mapa CSS con seis capas y un punto seleccionado.'),
 s('notifications','Notificaciones','/notificaciones',['Ciudadano'],'Notificaciones','UnifiedNotifications','Shell ciudadano','Campana, menú o acciones del sistema','Navegación inferior','implemented','Destinos almacenados en cada notificación.'),
 s('profile','Perfil','/perfil',['Ciudadano'],'Perfil','UnifiedProfile','Shell ciudadano','Avatar o navegación inferior','Navegación inferior','implemented','Resume cuidador, mascota, reserva y ruta.'),
 s('health','Salud','/salud',['Ciudadano','Visitante'],'Salud','HealthHome','Shell ciudadano','Inicio o servicios','Navegación inferior','implemented','Centro de los flujos sanitarios simulados.'),
 s('health-booking','Solicitar cita','/salud/reservar',['Ciudadano'],'Salud','AppointmentBooking','Shell ciudadano','Módulo salud o reprogramar','Volver a salud','implemented','Wizard de cinco selecciones y revisión.'),
 s('appointment-receipt','Comprobante de cita','/salud/citas/demo',['Ciudadano'],'Salud','AppointmentReceipt','Shell ciudadano','Inicio, salud, reserva o notificación','Volver a salud','implemented','Ruta parametrizada en código mediante cualquier segmento de citas.'),
 s('health-queue','Fila virtual','/salud/fila',['Ciudadano'],'Salud','Queue','Shell ciudadano','Módulo salud','Volver a salud','implemented','Comparte estado con agenda del encargado.'),
 s('health-caregiver','Familiar autorizado','/salud/familiar',['Ciudadano'],'Salud','Caregiver','Shell ciudadano','Salud o perfil','Volver a salud','implemented','Permisos granulares persistentes.'),
 s('clinical-history','Historial clínico simulado','/salud/historial',['Ciudadano'],'Salud','Clinical','Shell ciudadano','Módulo salud o notificación','Volver a salud','simulated','Datos clínicos completamente ficticios.'),
 s('clinical-share','Compartir historial','/salud/historial/compartir',['Ciudadano'],'Salud','Clinical','Shell ciudadano','Historial clínico','Volver a historial','simulated','Reautenticación local y QR visual.'),
 s('transport','Buscador de rutas','/transporte',['Ciudadano','Visitante'],'Transporte','TransportSearch','Shell ciudadano','Inicio, servicios o mapa','Navegación inferior','implemented','Origen, destino y preferencia controlados.'),
 s('multimodal-route','Ruta multimodal','/transporte/multimodal',['Ciudadano','Visitante'],'Transporte','Multimodal','Shell ciudadano','Calcular ruta','Volver a transporte','simulated','Tramos Pumakatari, Teleférico y caminata.'),
 s('route-alias','Ruta multimodal — alias','/transporte/ruta',['Ciudadano','Visitante'],'Transporte','Multimodal','Shell ciudadano','Mapa ciudadano heredado','Volver a transporte','partial','Alias conservado; muestra la misma pantalla que /transporte/multimodal.'),
 s('reports-list','Mis reportes','/reportes',['Ciudadano'],'Reportes','ReportList','Shell ciudadano','Inicio o servicios','Navegación inferior','implemented','Un caso compartido en la semilla.'),
 s('report-new','Nuevo reporte','/reportes/nuevo',['Ciudadano'],'Reportes','NewReport','Shell ciudadano','Inicio, reportes, ayuda o canchas','Volver a reportes','implemented','Incluye duplicado por categoría y zona.'),
 s('report-detail','Detalle de reporte','/reportes/[code]',['Ciudadano'],'Reportes','ReportDetail','Shell ciudadano','Lista, inicio o notificación','Volver a reportes','implemented','Chat, historial, evidencia, reapertura y calificación.', 'Código procedente del estado demo'),
 s('pets-list','Mascotas','/mascotas',['Ciudadano'],'Mascotas','Pets','Shell ciudadano','Inicio o servicios','Navegación inferior','implemented','Lista actual de una mascota.'),
 s('pet-registration','Registrar mascota','/mascotas/nueva',['Ciudadano'],'Mascotas','PetRegistration','Shell ciudadano','Lista de mascotas','Volver a mascotas','implemented','Genera credencial conceptual.'),
 s('pet-alert','Alerta de mascota','/mascotas/alertas/kira',['Ciudadano','Visitante'],'Mascotas','PetAlert','Shell ciudadano','Mascotas o notificación','Volver a mascotas','implemented','Avistamientos y cierre compartidos.'),
 s('courts-list','Canchas municipales','/canchas',['Ciudadano','Visitante'],'Canchas','CourtList','Shell ciudadano','Inicio o servicios','Navegación inferior','partial','Filtro funcional con una sola cancha.'),
 s('court-booking','Reservar cancha','/canchas/reservar',['Ciudadano'],'Canchas','CourtBooking','Shell ciudadano','Lista de canchas','Volver a canchas','simulated','Evita una segunda reserva activa.'),
 s('citizen-alerts','Alertas ciudadanas','/alertas',['Ciudadano','Visitante'],'Alertas','CitizenAlerts','Shell ciudadano','Inicio, servicios o notificación','Navegación inferior','partial','Muestra alerta y mapa; no tiene guardar, compartir ni preferencias.'),
 s('admin-home','Panel principal','/admin',['Administrador'],'Administración','Dashboard','AdminShell','Selector de demo','Cambiar vista','simulated','Métricas y tabla mayormente estáticas.', 'Rol admin'),
 s('admin-reports','Gestión de reportes','/admin/reportes',['Encargado municipal','Administrador'],'Reportes','AdminReportsFlow','AdminShell','Selector o menú lateral','Cambiar vista','implemented','Caso compartido con ciudadanía.', 'Rol reportes o admin'),
 s('admin-report-detail','Gestionar reporte','/admin/reportes/[code]',['Encargado municipal','Administrador'],'Reportes','AdminReportDetail','AdminShell','Tabla administrativa o mapa','Volver a reportes','implemented','Reglas obligatorias de asignación, rechazo y resolución.', 'Código del caso compartido'),
 s('admin-map','Mapa operativo','/admin/mapa',['Encargado municipal','Administrador'],'Mapa','MapVisual + panel','AdminShell','Menú lateral','Menú lateral','simulated','Mapa CSS; abre el reporte principal.', 'Rol reportes o admin'),
 s('admin-health','Agenda de salud','/admin/salud',['Encargado de salud','Administrador'],'Salud','HealthDesk','AdminShell','Selector o menú lateral','Cambiar vista','implemented','Actualiza cita, llegada, espera y consultorio.', 'Rol salud o admin'),
 s('medical-access','Acceso clínico temporal','/admin/salud/acceso-clinico',['Médico','Administrador'],'Salud','MedicalAccess','AdminShell','Selector de médico','Cambiar vista','simulated','Valida expiración y consumo del token.', 'Rol médico o admin; token activo'),
 s('admin-pets','Moderación de mascotas','/admin/mascotas',['Moderador de mascotas','Administrador'],'Mascotas','PetModeration','AdminShell','Selector o menú lateral','Cambiar vista','implemented','Estados compartidos y notificaciones.', 'Rol mascotas o admin'),
 s('admin-courts','Gestión deportiva','/admin/canchas',['Encargado deportivo','Administrador'],'Canchas','SportsDesk','AdminShell','Selector o menú lateral','Cambiar vista','implemented','Confirma reserva y estado de cancha.', 'Rol deportes o admin'),
 s('admin-alerts','Gestión de alertas','/admin/alertas',['Administrador'],'Alertas','AlertsDesk','AdminShell','Menú lateral','Cambiar vista','partial','Publica título, pero nivel y zona editados no se guardan.', 'Rol admin'),
 s('system-map','Mapa general del sistema','/equipo/mapa-sistema',['Documentación interna'],'Documentación','SystemDocumentation','System docs','Demo, panel o URL directa','Volver a demo','implemented','Seis pestañas tras esta actualización.', 'Clave opcional TEAM_DOCS_ACCESS_CODE'),
 s('navigation-wireflow','Wireflow de navegación','/equipo/flujo-navegacion',['Documentación interna'],'Documentación','NavigationWireflow','System docs','Mapa del sistema, demo, panel o URL directa','Volver al mapa','implemented','Tarjetas filtrables generadas desde este inventario.', 'Clave opcional TEAM_DOCS_ACCESS_CODE')
];

const routeMatches=(pattern:string,route:string)=>pattern===route||pattern.includes('[code]')&&route.startsWith(pattern.split('/[code]')[0]+'/')||pattern==='Ruta del módulo'||pattern==='Ruta inicial del rol'||pattern==='Destino almacenado'||pattern==='Ruta según capa'||pattern==='Ruta de la tarjeta';
export const navigationScreens:NavigationScreen[]=definitions.map(screen=>({...screen,entryPoints:navigationActions.filter(action=>action.destination&&routeMatches(screen.route,action.destination)),exitActions:navigationActions.filter(action=>action.origin===screen.id)}));
export const disconnectedActions=navigationActions.filter(action=>action.status==='broken');
export const partialActions=navigationActions.filter(action=>action.status==='partial');
export const unlistedScreens=navigationScreens.filter(screen=>screen.access.includes('URL directa')||screen.id==='route-alias');
